-- Deprecated.
--
-- Do not apply this migration. Document-upload ownership now uses:
--   leads.upload_mode
--   leads.upload_consent_uploader_lead_id
--
-- Apply sql/replace_submit_on_behalf_with_document_upload_choice.sql instead.
